[development]
[development.pgsql]
username = "postgres"
password = "mX1mHplUdHzZYLw3nJJHxw=="

[development.llama]
api_key="169af2770a27aa5ee37c60888588f27b"
[development.mysql]
username = "root"
password = "US1wGLwkpF6eDOoy"

[development.redis]
password = "redis_3JBx7S"

[development.minio]
access_key = "admin"
secret_key = "4sxuE7m5dxhoSsq3"

[production]
[production.redis]
password = "Pl5SpB72sllM8DsT"

[production.minio]
access_key = "admin"
secret_key = "4sxuE7m5dxhoSsq3"

[production.mysql]
username = "root"
password = "US1wGLwkpF6eDOoy"

[production.pgsql]
username = "postgres"
password = "mX1mHplUdHzZYLw3nJJHxw=="


[production.llama]
api_key="7061eec98127ea57523d51f23c0e9fe6"
