[development]
[development.pgsql]
username = "postgres"
password = "mX1mHplUdHzZYLw3nJJHxw=="

[development.llama]
api_key="7061eec98127ea57523d51f23c0e9fe6"
[development.llama_vl]
api_key_vl="7061eec98127ea57523d51f23c0e9fe6"

[development.mysql]
username = "root"
password = "US1wGLwkpF6eDOoy"

[development.redis]
password = "Pl5SpB72sllM8DsT"

[development.minio]
access_key = "minioadmin"
secret_key = "minioadmin"

[development.prompt]
username = "admin"
password = "admin123"
backend_token="Bearer 4525d65ec96c4e3abade57493ac3a171"


[production]
[production.redis]
password = "Pl5SpB72sllM8DsT"

[production.minio]
access_key = "admin"
secret_key = "4sxuE7m5dxhoSsq3"

[production.mysql]
username = "root"
password = "US1wGLwkpF6eDOoy"

[production.pgsql]
username = "postgres"
password = "mX1mHplUdHzZYLw3nJJHxw=="


[production.llama]
api_key="7061eec98127ea57523d51f23c0e9fe6"
[production.llama_vl]
api_key_vl="7061eec98127ea57523d51f23c0e9fe6"

[production.prompt]
username = "admin"
password = "admin123"
backend_token="Bearer 4525d65ec96c4e3abade57493ac3a171"
